module.exports = {
  "perGame.damagePg": "Avg. Damage/Game",
  "perGame.headshotKillsPg": "Avg. Headshots/Game",
  "perGame.healsPg": "Avg. Heals/Game",
  "perGame.killsPg": "Avg. Kills/Game",
  "perGame.moveDistancePg": "Avg. Move Distance/Game",
  "perGame.revivesPg": "Avg. Revives/Game",
  "distance.avgRideDistance": "Avg. Ride Distance",
  "perGame.roadKillsPg": "Avg. Road Kills/Game",
  "perGame.teamKillsPg": "Avg. Team Kills/Game",
  "survival.avgSurvivalTime": "Avg. Time Survived",
  "perGame.timeSurvivedPg": "Avg. Time Survived/Game",
  "perGame.top10sPg": "Avg. Top 10s/Game",
  "distance.avgWalkDistance": "Avg. Walk Distance",
  "skillRating.bestRank": "Best Rank",
  "skillRating.bestRating": "Best Rating",
  "combat.dailyKills": "Daily Kills",
  "defaultRegion": "Default Region",
  "defaultSeason": "Default Season",
  "combat.headshotKillRatio": "Headshot Kill Ratio",
  "performance.killDeathRatio": "Kill Death Ratio",
  "lastUpdated": "Last Updated Time",
  "rankData.kills": "Leaderboard Kills",
  "rankData.rating": "Leaderboard Rating",
  "rankData.winPoints": "Leaderboard Win Points",
  "rankData.wins": "Leaderboard Wins",
  "distance.longestKill": "Longest Kill",
  "survival.longestTimeSurvived": "Longest Time Survived",
  "performance.losses": "Losses",
  "match": "Match/Game Mode",
  "combat.maxKillStreaks": "Max Kill Streak",
  "combat.roundMostKills": "Most Kills in One Round",
  "survival.mostSurvivalTime": "Most Time Survived",
  "playerName": "Player Name",
  "skillRating.rating": "Rating",
  "region": "Region",
  "performance.roundsPlayed": "Rounds Played",
  "season": "Season",
  "performance.timeSurvived": "Time Survived",
  "performance.top10Ratio": "Top 10 Ratio",
  "performance.winTop10Ratio": "Top 10 Win Ratio",
  "performance.top10s": "Top 10 Wins",
  "combat.assists": "Total Assists",
  "support.boosts": "Total Boosts",
  "support.damageDealt": "Total Damage Dealt",
  "survival.days": "Total Days Alive",
  "combat.headshotKills": "Total Headshot Kills",
  "support.heals": "Total Heals",
  "combat.kills": "Total Kills",
  "support.dBNOs": "Total Knockouts",
  "distance.moveDistance": "Total Move Distance",
  "support.revives": "Total Revives",
  "distance.rideDistance": "Total Ride Distance",
  "combat.roadKills": "Total Road Kills",
  "combat.suicides": "Total Suicides",
  "combat.teamKills": "Total Team Kills",
  "combat.vehicleDestroys": "Total Vehicle Destroys",
  "distance.walkDistance": "Total Walk Distance",
  "combat.weaponAcquired": "Weapons Acquired",
  "combat.weeklyKills": "Weekly Kills",
  "performance.winPoints": "Win Points",
  "performance.winRatio": "Win Ratio",
  "performance.wins": "Wins",
};
